---
include:
  - board: blecorne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    shield: nice_view_adapter nice_view_gem
  - board: blecorne_right
    shield: nice_view_adapter nice_view_gem
