---
include:
  - board: blecorne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    shield: nice_view
  - board: blecorne_right
    shield: nice_view
  - board: blecorne_left
    snippet: settings_reset
  - board: blecorne_right
    snippet: settings_reset
